entryPoints:
  web:
    address: ":80"
  websecure:
    address: ":443"
  traefik:                # este nombre es importante
    address: ":9000"      # expone el dashboard por este puerto

api:
  dashboard: true
  insecure: true          # visible directamente por el puerto 9000 (solo en red local)

providers:
  docker:
    exposedByDefault: false

  file:
    directory: /dynamic  # Aquí buscará toda tu config dinámica
    watch: true

certificatesResolvers:
  letsencrypt:
    acme:
      email: taikunchannel@gmail.com
      storage: acme.json
      httpChallenge:
        entryPoint: web

accessLog:
  filePath: /var/log/traefik/access.log
  bufferingSize: 100

experimental:
  plugins:
    crowdsec-bouncer-traefik-plugin:
      moduleName: "github.com/maxlerebourg/crowdsec-bouncer-traefik-plugin"
      version: "v1.4.2"
    fail2ban:
      moduleName: "github.com/tomMoulard/fail2ban"
      version: "v0.8.3"
